workspace/xreferences: change WorkspaceReferencesParams.files to .hints
sourcegraph/language-server-protocol pull request #10
Opened 2017-01-09 02:28 UTC by slimsag

This more appropriately represents the data at hand. A language server
may choose any hints -- not just files. These are primarily derived from
a build server's workspace/xdependencies method results.

2017-01-09 04:15 UTC, felixfbecker commented
Could you give some examples?

2017-01-10 19:43 UTC, beyang approved these changes
LGTM.

@felixfbecker This makes it possible to include other types of hints that aren't a list of files. For instance, in some languages, a list of packages or directories might be more appropriate.

2017-01-10 20:57 UTC, felixfbecker requested changes
Do you plan to ever propose workspace/xreferences upstream? Putting the hints in the same interface makes it hard to extend it later, might put it under `hints` property

2017-01-10 20:57 UTC, felixfbecker commented on extension-workspace-references.md
> +    [hints: string]: any;
key should be singular (`hint`).

2017-01-11 19:28 UTC, beyang commented
agree with making `hints` its own field.

2017-01-13 02:29 UTC, beyang commented on extension-workspace-references.md
> +    [hints: string]: any;
After discussion with Stephen, propose to change this to:
```
hints: {
    [hint: string]: any;
}
```

2017-02-03 20:48 UTC, slimsag commented
Merging this on the grounds that it accurately reflects what we do, at least for Go, today. I still agree we should switch to xdependencies -- this doesn't change that :)

I confirmed with @felixfbecker that we should keep our spec up to date / that he's ok with me merging this.

2017-02-03 20:48 UTC, merged