workspace/xpackages
sourcegraph/language-server-protocol pull request #16
Opened 2017-01-21 00:07 UTC by beyang

2017-01-21 09:30 UTC, felixfbecker requested changes

2017-01-21 09:30 UTC, felixfbecker commented on extension-workspace-references.md
> +	[attr: string]: any;
Aren't we using very specific attributes in Sourcegraph? If yes, lets spec them.

2017-01-21 09:30 UTC, felixfbecker commented on extension-workspace-references.md
> +interface PackageDescriptor {
The difference between `PackageDescriptor` and `PackageInformation` is not clear to me. Why do we need two interfaces that describe a package?

2017-01-23 18:14 UTC, beyang commented on extension-workspace-references.md
> +interface PackageDescriptor {
Good point. I think we should also have a `PackageDescriptor` field in `SymbolDescriptor`. We need to extract the former from the latter.

2018-11-02 07:25 UTC, closed without merging